[workspace]
members = ["cryptography", "protocol"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/FreeAndFair/MobileVotingCoreCryptography"

[workspace.dependencies]
