# .github/workflows/build-release.yml
# Author: Daniel M. Zimmerman
# Created: 2025-01-22
# Modified: 2026-02-06

# This workflow creates a "Latest" release with all the release artifacts
# from this repository

name: Build and Release Artifacts

on:
  push:
    branches:
      - 'main'

    paths:
      - 'models/threat-model/**'
      - 'docs/papers/refinements_among_high_level_models/**'
      - 'docs/faq/**'

  workflow_dispatch:

jobs:
  release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Packages
        run: sudo apt-get install build-essential

      - name: Install/Restore TeXLive Environment
        uses: FreeAndFair/setup-texlive-action@v3
        with:
          packages: |
            scheme-full

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Render Threat Model PDF and HTML
        run: |
          cd models/threat-model
          pip install -r requirements.txt
          make graph pdf

      - name: Render Refinements Paper
        run: |
          cd docs/papers/refinements_among_high_level_models
          latexmk --pdf refinements_paper.tex

      - name: Render FAQ
        run: |
          cd docs/faq
          latexmk --pdf faq.tex

      - name: Release Generated Files
        uses: FreeAndFair/action-gh-create-release@v5.0.1
        with:
          strategy: replace
          tag: latest
          tag-message: The latest build of the main branch.
          body: This is the latest build of E2E-VIV artifacts from the main branch.
          title: Latest
          prerelease: true
          files: |
            CHANGELOG.md
            models/threat-model/threat-model.pdf
            models/threat-model/threat-model.html
            docs/papers/refinements_among_high_level_models/refinements_paper.pdf
            docs/faq/faq.pdf
